spring.application.name=workshopmongo
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/workshop_mongo
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=never
server.error.include-binding-errors=never